[package]
name = "genart"
version = "0.1.0"
edition = "2021"
authors = ["Benedikt Zoennchen <benedikt.zoennchen@web.de>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.19.0"
rand = "0.8.5"
time = "0.3.31"