[package]
name = "polyphony"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = {version = "0.18.1"}
nannou_osc = "0.18.0"
nannou_egui = "0.5.0"
rand_distr = "0.4.3"